<?php 
$students = [
    [
        "firstName" => "James",
        "lastName" => "Fields",
        "grades" => [12, 11, 15],
        "average" => -1
    ],
    [
        "firstName" => "Richard",
        "lastName" => "Stein",
        "grades" => [18, 12, 13],
        "average" => -1
    ],
    [
        "firstName" => "Mark",
        "lastName" => "Hartoff",
        "grades" => [9, 11, 10],
        "average" => -1
    ],
    [
        "firstName" => "Thomas",
        "lastName" => "Nestle",
        "grades" => [9, 8, 5],
        "average" => -1
    ],
    [
        "firstName" => "Jeremy",
        "lastName" => "Brent",
        "grades" => [18, 15, 16],
        "average" => -1
    ]
];


function average($nb1)
{
    $somme_notes = 0;
    $i = 0;
    foreach($nb1 as $cle => $valeur)
    {
        $i++; 
        $somme_notes = $somme_notes + $valeur;
    }
    $moyenne = $somme_notes / $i;

    return round($moyenne, 2);
}

function colorAverage(){
    
}
?>


<!DOCTYPE html>
<html lang="fr" prefix="og: https://ogp.me/ns#">
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <title>Titre de la page</title>
      <link rel="stylesheet" href="style.css">
      
    </head>
    <body>
        <?php
        foreach($students as $student){
        
        ?>
        <article class="">
            <header>
                <h1>
                    <?php
                    echo "{$student['firstName']} {$student['lastName']}";
                    ?>
                </h1>
            </header>
            <section>
                <h2>Notes : </h2>
                <ul>
                    <?php 
                        for($i = 0; $i < count($student['grades']); $i++)
                        {
                    ?>
                    <li>
                        <?php
                            echo "{$student['grades'][$i]}";
                        ?>
                    </li>
                    <?php
                        }
                    ?>
                </ul>
            </section>
            <footer>
                <h3>
                    <?php
                        echo average($student['grades']);
                    ?>
                </h3>
            </footer>
        </article>
        <?php
            }
        ?>
    </body>
</html>

